{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "70566c7a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "import psycopg2\n",
    "\n",
    "# -------------------------------\n",
    "# CONFIG\n",
    "# -------------------------------\n",
    "LATITUDE = 13.0827\n",
    "LONGITUDE = 80.2707\n",
    "\n",
    "DB_CONFIG = {\n",
    "    \"host\": \"postgres\",\n",
    "    \"database\": \"postgres\",\n",
    "    \"user\": \"postgres\",\n",
    "    \"password\": \"postgres\",\n",
    "    \"port\": \"5432\"\n",
    "}\n",
    "\n",
    "# -------------------------------\n",
    "# EXTRACT\n",
    "# -------------------------------\n",
    "def extract_weather_data():\n",
    "    url = f\"https://api.open-meteo.com/v1/forecast?latitude={LATITUDE}&longitude={LONGITUDE}&current_weather=true\"\n",
    "    \n",
    "    try:\n",
    "        response = requests.get(url, timeout=10)\n",
    "        response.raise_for_status()\n",
    "        return response.json()\n",
    "    except Exception as e:\n",
    "        raise Exception(f\"API Error: {e}\")\n",
    "\n",
    "# -------------------------------\n",
    "# TRANSFORM\n",
    "# -------------------------------\n",
    "def transform_weather_data(data):\n",
    "    current = data.get(\"current_weather\", {})\n",
    "    \n",
    "    transformed = {\n",
    "        \"latitude\": data.get(\"latitude\"),\n",
    "        \"longitude\": data.get(\"longitude\"),\n",
    "        \"temperature\": current.get(\"temperature\"),\n",
    "        \"windspeed\": current.get(\"windspeed\"),\n",
    "        \"winddirection\": current.get(\"winddirection\")\n",
    "    }\n",
    "    \n",
    "    return transformed\n",
    "\n",
    "# -------------------------------\n",
    "# LOAD\n",
    "# -------------------------------\n",
    "def load_weather_data(data):\n",
    "    conn = psycopg2.connect(**DB_CONFIG)\n",
    "    cursor = conn.cursor()\n",
    "\n",
    "    # Create table\n",
    "    cursor.execute(\"\"\"\n",
    "        CREATE TABLE IF NOT EXISTS weather_data (\n",
    "            id SERIAL PRIMARY KEY,\n",
    "            latitude FLOAT,\n",
    "            longitude FLOAT,\n",
    "            temperature FLOAT,\n",
    "            windspeed FLOAT,\n",
    "            winddirection FLOAT,\n",
    "            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n",
    "        );\n",
    "    \"\"\")\n",
    "\n",
    "    # Insert data\n",
    "    cursor.execute(\"\"\"\n",
    "        INSERT INTO weather_data (latitude, longitude, temperature, windspeed, winddirection)\n",
    "        VALUES (%s, %s, %s, %s, %s);\n",
    "    \"\"\", (\n",
    "        data[\"latitude\"],\n",
    "        data[\"longitude\"],\n",
    "        data[\"temperature\"],\n",
    "        data[\"windspeed\"],\n",
    "        data[\"winddirection\"]\n",
    "    ))\n",
    "\n",
    "    conn.commit()\n",
    "    cursor.close()\n",
    "    conn.close()\n",
    "\n",
    "# -------------------------------\n",
    "# MAIN FUNCTION\n",
    "# -------------------------------\n",
    "def run_etl():\n",
    "    data = extract_weather_data()\n",
    "    transformed = transform_weather_data(data)\n",
    "    load_weather_data(transformed)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
